services:
  nginx:
    image: nginx
    hostname: astra-nginx
    container_name: astra-nginx
    restart: unless-stopped
    volumes:
      - ./nginx/logs:/var/log/nginx #log файлы.
      - ./nginx/srv.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    networks:
      - astra_net
    depends_on:
      - bot
  bot:
#    build: ./bot
    image: hanmaster/bot:latest
    hostname: astra-bot
    container_name: astra-bot
    restart: always
    environment:
      - RUST_LOG
      - API_URL
      - ID_INSTANCE
      - API_TOKEN_INSTANCE
      - ADMIN_CHAT_ID
      - WORKER_PORT
      - SHOP_ADDRESS
      - SHOP_PHONE
      - NO_FILES_TIMEOUT
      - REPEAT_COUNT
      - REPEAT_TIMEOUT
      - HOOK_PORT
      - SECRET_TOKEN
      - PAPER_PROMPT
      - SIZE_PROMPT
      - FILES_DONE_PROMPT
    ports:
      - "${HOOK_PORT}:${HOOK_PORT}"
    networks:
      - astra_net
    depends_on:
      - worker

  worker:
#    build: ./worker
    image: hanmaster/worker:latest
    hostname: astra-worker
    container_name: astra-worker
    restart: always
    volumes:
      - ${WORK_DIR}:/orders
    environment:
      - RUST_LOG
      - WORKER_PORT
      - START_COUNTER
      - SMTP_SERVER
      - SMTP_PORT
      - SENDER_EMAIL
      - SENDER_PASS
      - RECEIVER_EMAIL
    ports:
      - "${WORKER_PORT}:${WORKER_PORT}"
    networks:
      - astra_net

networks:
  astra_net:
    driver: bridge